tracker/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from registration.views import register


from django.contrib import admin
admin.autodiscover()

from timetracker.views import *

urlpatterns = patterns('',

    url(r'^$', home, name="home"),
    #url(r'^api/next-month/(?P<current>[\w-]+)/$', next_month, name="next_month"),
    
    
    
    url(r'^url/make/$', make_url, name="make_url"),
    url(r'^url/(?P<hashkey>[\w-]+)/$', view_url, name="view_url"),
    url(r'^usersettings/$', usersettings, name="usersettings"),
    url(r'^tour/one/$', direct_to_template, {'template': 'timetracker/tour_1.html',}),
    url(r'^tour/two/$', direct_to_template, {'template': 'timetracker/tour_2.html',}),

    url(r'^ical/(?P<owner_id>\d+)/jobs.ics$', ical, name="jobs_ical"),
    
    url(r'^job/(?P<hashkey>[\w-]+)/delete$', delete_job, name="delete_job"),
    url(r'^job/(?P<hashkey>[\w-]+)/done$', mark_job_as_done, name="job_done"),
    url(r'^job/(?P<hashkey>[\w-]+)/paid$', mark_job_as_paid, name="job_paid"),
    url(r'^job/(?P<hashkey>[\w-]+)/$', job, name="job"),
    url(r'^add-job/$', addjob, name="addjob"),
    url(r'^anonymous-login/$', anonymous_login, name="anonymous_login"),
    
    url(r'^accounts/register/$', register,
        {'backend': 'tracker.regbackend.CustomBackend',},        
        name='registration_register'
    ),
    
    
    # api-like urls
    url(r'^load-stats/$', load_stats, name="load_stats"),
    url(r'^load-jobs/$', load_jobs, name="load_jobs"),
    url(r'^update-job/$', update_job, name="update_job"),
    

    (r'^accounts/', include('registration.backends.default.urls')),


    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

timetracker/forms.py
from django import forms


class AddForm(forms.Form):
    details = forms.CharField(max_length=200, required=False)
    start_date = forms.CharField(required=False)
    
    rate = forms.CharField(required=False)
    time = forms.CharField(required=False)
    start_time_hours = forms.CharField(required=False)
    start_time_mins = forms.CharField(required=False)
    start_time_ampm = forms.CharField(required=False)
    client = forms.CharField(required=False)
    name = forms.CharField(required=False)
    currency = forms.CharField(required=False)


class MakeURLForm(forms.Form):
    can_write = forms.BooleanField(required=False)
    can_see_names = forms.BooleanField(required=False)
    can_see_details = forms.BooleanField(required=False)

tracker/templates/mobile/snippets/add-form.html
<div data-role="page" id="addForm">

  <div data-role="content">
    <form id="add-form" action="{% url addjob %}" method="post">
        {% csrf_token %}
        
        <p>Add a job or appointment with the fields below:</p>
        
        <input type="hidden" class="hidden" name="details" id="id_details">
        <div data-role="fieldcontain">
            <label for="start_date" class="hidden">Date</label>
            <input type="date" id="id_start_date" name="start_date" value="{{ today|date:'Y-m-d' }}" class="hidden" />
		</div>
		
		<div data-role="fieldcontain">
            <label class="ui-input-text" for="name">Name</label>
            <input type="text" name="name" id="id_name" value="" />
        </div>
        
        <div data-role="fieldcontain">
            <label class="ui-input-text" for="client">Client</label>
            <select name="client" id="id_client">
                {% for x in clientnames %}
               <option value="{{ x }}">{{ x }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div data-role="fieldcontain">
            
            <label class="ui-input-text" for="start_time">Start time</label>
            
            <fieldset data-role="controlgroup" data-type="horizontal"> 
            <select name="start_time_hours" id="id_start_time_hours">
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
            <select name="start_time_mins" id="id_start_time_mins">
                <option value="00">0</option>
                <option value="05">5</option>
                <option value="10">10</option>
                <option value="15">15</option>
                <option value="20">20</option>
                <option value="25">25</option>
                <option value="30">30</option>
                <option value="35">35</option>
                <option value="40">40</option>
                <option value="45">45</option>
                <option value="50">50</option>
                <option value="55">55</option>
            </select>
            <select name="start_time_ampm" id="id_start_time_ampm">
                <option value="am">a.m.</option>
                <option value="pm">p.m.</option>
            </select>
            </fieldset>
        </div>
		
		<div data-role="fieldcontain">
		  <label class="ui-input-text" for="rate">Rate</label>
		  <input type="range" name="rate" id="id_rate" value="60" min="0" max="100" data-highlight="true" step="10">
		</div>
		<div data-role="fieldcontain">
		  <label class="ui-input-text" for="time">Length (hrs)</label>
		  <input type="range" name="time" id="id_time" val="" value="2" min="0" max="12" step="0.1" data-highlight="true">
		</div>
        	
        
        <fieldset class="ui-grid-a">
    	   <div class="ui-block-a"><a href="#mainContent" data-theme="c" data-rel="back" data-role="button">Cancel</a></div>
    	   <div class="ui-block-b"><input type="submit" value="Save" data-theme="b" /></div>
        </fieldset>
        
    </form>
  </div>
</div>

tracker/templates/mobile/snippets/day_cell.html
{% if day|safe == '1' %}
</p>
{% endif %}

{% if day %}
<li id="{{ year }}-{{ month }}-{{ day }}" data-role="list-divider" class="{{ cssclass }}">
    <h3>{{ day|safe }}</h3>
</li>
{% if body %}{{ body|safe|removetags:"ul" }}{% endif %}
{% endif %}

tracker/templates/mobile/snippets/footer.html
<div id="footer" data-role="footer" data-position="fixed" data-id="footer"> 
  <div data-role="navbar">   
    <ul>
        <li><a data-role="button" data-icon="plus" data-iconpos="left" href="#addForm" data-rel="dialog">Add</a></li>
        <li><a data-role="button" data-icon="home" data-iconpos="left" href="#home">Home</a></li>
        <li><a data-role="button" data-icon="info" data-iconpos="left" href="#stats" data-rel="dialog">Stats</a></li>
    </ul>
  </div>
</div>

tracker/templates/mobile/snippets/header.html
<div id="header" data-role="header" data-id="header">
    <h1>{{ date|date:"M Y" }}</h1>
</div>

tracker/templates/mobile/snippets/job_details.html
<div class="right-buttons">
    <a id="done" {% if job.completed %}class="done"{% endif %} href="{% url job_done job.hashkey %}">Done</a>
    <a id="paid" {% if job.paid %}class="done"{% endif %} href="{% url job_paid job.hashkey %}">Paid</a>
</div>

<div class="left-content">
    <h4>{{ job.name }} ({{ job.client }})</h4>
    {{ job.start_date_time|time:"H:i" }} - {{ job.get_end_time|time:"H:i" }} ({{ job.length|floatformat }}hrs)
    <br/>{{ job.rate }} {{ job.currency.code }}
    <a id="delete" href="{% url delete_job job.hashkey %}">Delete </a>
</div>

tracker/templates/mobile/snippets/job_link.html
<li><a href="{{ job.get_absolute_url }}" class="link{% if job.completed %} done{% endif %}{% if job.paid %} paid{% endif %}">{{ job }}</a></li>

tracker/templates/mobile/snippets/stats.html
<div data-role="page" id="stats">
  <div data-role="content">
  	 
  	 <ul>
          {% for x in clients %}
          <li><strong>{{ x.name|capfirst }} ({{ x.money|floatformat }})</strong></li>
          {% endfor %}
            
            {% if total_money %}<li><strong>Total money:</strong> {{ total_money }}</li>{% endif %}
            {% if paid %}<li><strong>Total paid:</strong> {{ paid }}</li>{% endif %}
            {% if completed %}<li><strong>Total completed:</strong> {{ completed }}</li>{% endif %}
            {% if av %}<li><strong>Average daily:</strong> {{ av }}</li>{% endif %}
	 </ul>
	 <a href="#mainContent" data-rel="back" data-role="button" data-inset="true">Back</a>
  </div>
</div>